[server]
port = "8080"
url = "http://atlas.oraxen.com:8080"

[request]
max_size = 100000000 # 100 MB

[cleaner]
delay = 21600 # every 6 hours
pack_lifespan = 604800 # remove a pack after 7 days without downloads